### ISSUE TITLE
ios15 safari対応

### ISSUE THREAD

**Issue by amatotsuji** [seibii/saiyo-yatteiki#7]
https://jp.techcrunch.com/2021/07/28/2021-07-27-apple-tweaks-controversial-ios-15-safari-changes-in-latest-beta/

アドレスバーの位置が変わったので、それへの対応検討について記事にする。
単純に需要ありそうだし、開発フローを具体的な事例沿ってオープンにできる機会だしという理由で

**Comment by yuta-sanada0089** [comment]
特に対応なかったので閉じ
